name: Deploy to S3

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: oven-sh/setup-bun@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Convert tokens
      run: |
        sudo apt-get install ffmpeg
        ./.script/convert.sh
        
    - name: Build index.html
      run: |
        bun run .preview/build.ts

    - name: Sync S3 bucket
      run: |
        aws s3 sync . s3://kodiak-static --delete --exclude ".*" --exclude "src/*"
      env:
        S3_BUCKET_NAME: kodiak-static

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"